[dependencies]
av = "*"

[cuda]
packages = ["sageattention", "flash_attn"]

[pypi-dependencies]
huggingface_hub = "*"
trimesh = ">=4.0"
scipy = "*"
matplotlib = "*"
pillow = "*"
opencv-python-headless = "*"
utils3d = { git = "https://github.com/EasternJournalist/utils3d.git", rev = "3fab839f0be9931dac7c8488eb0e1600c236e183" }
